### ISSUE TITLE
Effective replica count of multi zone machines can be higher than the requested one

### ISSUE THREAD

**Issue by corvus-ch** [appuio/component-openshift4-nodes#3]
When defining a multi AZ node group, the resulting sum of replicas will always be rounded up to a multiple of availability zone count. This can be higher than the requested ones and lead to additional costs.

## Steps to Reproduce the Problem

```yaml
nodeGroups:
  worker:
    replicas: 4
    multiAz: true
availabilityZones:
    - europe-west6-a
    - europe-west6-b
    - europe-west6-c
```

## Actual Behavior

Three MachineSets each with a replicas of 2 and thus a total of 6 machines.

## Expected Behavior

Three MachineSets. One with a replica set to 2 and two with a replica set to 1.

## Workaround

```yaml
nodeGroups:
  worker-a:
    replicas: 2
    multiAz: false
  spec:
    template:
      spec:
        providerSpec:
          zone: europe-west6-a
  worker-b:
    replicas: 1
    multiAz: false
  spec:
    template:
      spec:
        providerSpec:
          zone: europe-west6-b
  worker-c:
    replicas: 1
    multiAz: false
  spec:
    template:
      spec:
        providerSpec:
          zone: europe-west6-c
```
